version: '3.8'

services:
  heatmap:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app.js:/usr/share/nginx/html/app.js
      - ./index.html:/usr/share/nginx/html/index.html
      - ./data:/usr/share/nginx/html/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s